name = "Voyager Compass";
picture = "\k\ugtx\addons\compass\data\ui\logo_voyager_compass_ca.paa";
actionName = "Website";
action = "https://arma.kestrelstudios.co.uk";
description = "A PUBG style compass for Arma 3.";
logo = "\k\ugtx\addons\compass\data\ui\logo_voyager_compass_ca.paa"
logoOver = "\k\ugtx\addons\compass\data\ui\logo_voyager_compass_ca.paa"
tooltip = "Voyager Cpmpass";
overview = "A PUBG style compass for Arma 3.";
author = "Unknown GTX & Flax";
overviewPicture = "\k\ugtx\addons\compass\data\ui\logo_voyager_compass_ca.paa"
